import = [
    "~/.config/alacritty/themes/themes/papercolor_light.toml"
]

[font]
normal = { family = "BlexMono Nerd Font", style = "Regular"} 
size = 14

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[shell]
program = "/opt/homebrew/bin/tmux"
