import = [
    "~/.config/alacritty/themes/themes/papercolor_light.toml"
]

[font]
normal = { family = "BlexMono Nerd Font", style = "Regular"} 
size = 14

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
chars = "\u001BF"
key =  "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
mods = "Alt"
key = "Left"
