modmap:
  - name: Caps-to-esc
    remap:
      CapsLock: Esc
  - name: win-alt-swap
    device:
      only: ['AT Translated Set 2 keyboard']
    remap:
      Win_L: Alt_L
      Alt_L: Win_L
      Alt_R: Win_R

keymap:
  - name: Vim-like navigation
    remap:
      Win-h: Left
      Win-j: Down
      Win-k: Up
      Win-l: Right
  - name: Chromium
    application:
      only: [Chromium]
    remap:
      Win-c: C-c
      Win-n: C-n
      Win-v: C-v
      Win-t: C-t
      Win-w: C-w
      Win-r: C-r
      Win-f: C-f
