modmap:
  - name: Caps-to-esc
    remap:
      CapsLock: Esc

keymap:
  - name: Vim-like navigation
    remap:
      Win_R-h: Left
      Win_R-j: Down
      Win_R-k: Up
      Win_R-l: Right
  - name: Ctrl mapping
    remap:
      Win_L-c: CTRL-c
      Win_L-v: CTRL-SHIFT-v
